version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: social-media-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: social-media
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - social-media-network

  mongo-express:
    image: mongo-express:latest
    container_name: social-media-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongodb:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongodb
    networks:
      - social-media-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: social-media-server
    restart: unless-stopped
    ports:
      - "3001:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/social-media
      - JWT_SECRET=your_jwt_secret_key_change_this_in_production
      - JWT_EXPIRE=24h
      - NODE_ENV=development
    depends_on:
      - mongodb
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - social-media-network

networks:
  social-media-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local