version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: social-media-ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - social-media-network

  mongodb:
    image: mongo:latest
    container_name: social-media-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: social-media
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - social-media-network

  mongo-express:
    image: mongo-express:latest
    container_name: social-media-mongo-express
    restart: unless-stopped
    ports:
      - "8082:8081"
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongodb:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongodb
    networks:
      - social-media-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: social-media-server
    restart: unless-stopped
    ports:
      - "3001:3001"  # HTTP API + WebSocket on same port
    environment:
      - PORT=3001
      - MONGODB_URI=mongodb://mongodb:27017/social-media
      - JWT_SECRET=your_jwt_secret_key_change_this_in_production
      - JWT_EXPIRE=24h
      - NODE_ENV=development
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_MODEL=llama3.2
      - AI_TEMPERATURE=0.7
      - AI_MAX_TOKENS=500
    depends_on:
      - mongodb
      - ollama
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - social-media-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: social-media-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"  # React development server
    environment:
      - REACT_APP_API_URL=http://localhost:3001/api
      - REACT_APP_WS_URL=ws://localhost:3001/chat
      - CHOKIDAR_USEPOLLING=true  # Enable hot reload in Docker
      - WATCHPACK_POLLING=true
    depends_on:
      - server
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - social-media-network
    stdin_open: true  # Required for React
    tty: true  # Required for React

networks:
  social-media-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  ollama_data:
    driver: local